/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_cserialportCSharp_WRAP_H_
#define SWIG_cserialportCSharp_WRAP_H_

class SwigDirector_CSerialPortListener : public itas109::CSerialPortListener, public Swig::Director {

public:
    SwigDirector_CSerialPortListener();
    virtual ~SwigDirector_CSerialPortListener();
    virtual void onReadEvent(char const *portName,unsigned int readBufferLen);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(char *, unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackonReadEvent);

private:
    SWIG_Callback0_t swig_callbackonReadEvent;
    void swig_init_callbacks();
};


#endif
